### ISSUE TITLE
template migrated from Stage to Dev has fields in wrong order

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_migration#2]
compare https://development.sinopia.io/editor/Sinopia:RT:Demo:SampleResourceFuller and https://stage.sinopia.io/editor/Sinopia:RT:Demo:SampleResourceFuller

fields are called "field 1", "field 2", etc and are shown in that order in Stage, but after template was migrated to Dev, fields 2, 4, 5, and 6 are not in order any more.

have not found any other templates with this issue

**Comment by justinlittman** [comment]
This should be resolved. Can you verify (and close) @michelleif ?

**Comment by michelleif** [comment]
verified that fields are displaying in proper order now for https://development.sinopia.io/editor/Sinopia:RT:Demo:SampleResourceFuller 

(note that in Preview, the statements are not "in order" because RDF does not have order per se)
