### ISSUE TITLE
change all Trellis URIs to Sinopia API URIs in all resources

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_migration#5]
some records (resources) use Trellis URIs to refer to other records, like https://api.development.sinopia.io/repository/stanford/e3a36ad9-dfb4-46fa-b588-f7d7bebd2a37 in the "Administrative Metadata" field

these Trellis URIs need to be updated to corresponding Sinopia API URIs in all resources so that the references will still work

**Comment by justinlittman** [comment]
Here is a record that references another Sinopia record: https://trellis.development.sinopia.io/repository/stanford/8042cec3-25f5-4d39-ac42-c02178e5f142
